server {
    listen 80;
    server_name localhost;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/v1/auth {
        set $target_auth auth-service:8001;
        proxy_pass http://$target_auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/provisioning {
        set $target_prov db-provisioning-service:8001;
        proxy_pass http://$target_prov;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/helm {
        set $target_helm helm-deployer:8001;
        proxy_pass http://$target_helm;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/cost {
        set $target_cost cost-management-service:8001;
        proxy_pass http://$target_cost;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/operator {
        set $target_op operator-service:8001;
        proxy_pass http://$target_op;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/discovery {
        set $target_disc discovery-service:8001;
        proxy_pass http://$target_disc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/catalog {
        set $target_cat db-info-service:8001;
        proxy_pass http://$target_cat;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/provider {
        set $target_prov_svc provider-service:8001;
        proxy_pass http://$target_prov_svc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/vault {
        set $target_vault vault-service:8001;
        proxy_pass http://$target_vault;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
